### PR TITLE
Fix memory leaks

### LINKED ISSUE #2: OBS Shaderfilter leaks tonnes of memory even if it isn't used at all.
If OBS Shaderfilter is installed into a brand new never used OBS installation (OBS 27.2.4 used in testing), and OBS is started up and then immediately exited, with no scenes added and no filters being used, OBS will exit with a log file indicating that over 3000 memory leaks were detected.  If OBS Shaderfilter is removed, this goes down to 1 memory leak.

### PR DESCRIPTION
**Pull request by norihiro**
### Description

This PR fixes the mamory leaks that I found.
Also skip processing the shader if gs_effect_create returns NULL.

### Motivation
Just using the shader filter, it leaks a lot of memory.

This PR is same as https://github.com/Oncorporation/obs-shaderfilter/pull/10.

### How has been tested

Tested on my Linux machine. Details are described in above PR.

### CODE REVIEW

File: src/obs-shaderfilter.c [hunk 1]
```diff
@@ -262,6 +262,8 @@ static void shader_filter_reload_effect(struct shader_filter_data *filter)
 	if (filter->effect == NULL)
 	{
 		blog(LOG_WARNING, "[obs-shaderfilter] Unable to create effect. Errors returned from parser:\n%s", (errors == NULL || strlen(errors) == 0 ? "(None)" : errors));
+		bfree(errors);
```
Comment (skeletonbow) [inline src/obs-shaderfilter.c:265]: Should this bfree() only be done if errors is not NULL?

Comment (skeletonbow) [reply src/obs-shaderfilter.c:265]: Ah nevermind, I found the bfree() implementation in OBS and it does the NULL check internally.
